### ISSUE TITLE
Installation failed on mac os

### ISSUE THREAD

**Issue by jurgob** [jonniespratley/angular-cms#14]
I've followed the readme.md instruction but:

if I access to http://localhost:8181/ I've just the list of directory's files.
if I access to http://localhost:8181/index.html I get "Cannot GET /index.html" message

additional notes.
when I execute node server I have the following warning:
Listening on port: 8181
Socket.IO's `listen()` method expects an `http.Server` instance
as its first parameter. Are you migrating from Express 2.x to 3.x?
If so, check out the "Socket.IO compatibility" section at:
https://github.com/visionmedia/express/wiki/Migrating-from-2.x-to-3.x

**Comment by jonniespratley** [comment]
I am currently going to fix the issues with migration. As for the viewing the server. `$ node server` will only render files that are located in the dist directory, make sure you run `$ grunt build` before running `$ node server` if you want to view the production site. But for development you will still run `$ node server` because that is where the API will be living, and then `$ grunt serve` to start up the development server that proxys requests to the node server instance. 

So for development;
1. `$ sh bin/db.sh` => `$ node server` =>  `$ grunt serve` => localhost:9000 => proxy api => localhost:8181
