### ISSUE TITLE
Better readme file / Project status

### ISSUE THREAD

**Issue by jkarttunen** [jonniespratley/angular-cms#9]
Hi,

It is really difficult to figure out the status of project from the readme file. Especially since the heroku app seems to be down. I was trying to figure out if i can start building stuff on angular-cms, but the scenarios and wireframes on readme makes this look like the project is on early concepting phase. IMHO it would be useful to have quick intro on project and project status on the readme file. (Still trying to figure out if this is something i should watch, use now, use later or possibly start contributing)

**Comment by jonniespratley** [comment]
Ok I will get an update. This is on the back burner right now and only when I have time in between writing this yeoman book and working at ge software. But I have plans to update the readme soon Nd clean up the branches. 

Todos:

Getting started - starting mongo, starting node, starting grunt 
Basics - user login/ register / forgot - finish up client logic and fix server logic in rest.js

Advanced: 

Unit tests for auth service and data service for dynamic rest to the back end.
Drag drop sort widgets loaded from registered plugins based on confit file or from db + unit + e2e
Install bower components from UI into server directory and load module by (update format) scripts. Amd commonjs angular etc.

Make theme management use installs le themes instead of static hosted a track space.

Fix heroku server file.

Ill add more and clean up once off ipad. 

Tasks:

Clean up server.js and rest.js and wire up socket server for crud thru socket fallback rest.

**Comment by jonniespratley** [comment]
Done.
